### ISSUE TITLE
is node >12.22 necessary to use this library on browser side?

### ISSUE THREAD

**Issue by vishnu-shekhawat** [komodojp/tinyld#5]
Hi ,

we are working on some e2e test cases on our end , which are written in cypress. and since our system is legacy we have 12.18 node version and we want to use this library for our work.

is it possible to use just browser side library w/o worrying about nodejs version?
could we fork and try it with nodejs 12.18 version on our end and use it ?

**Comment by kefniark** [comment]
if it's purely for browser usage, you can directly use the CDN version (in ESM).
https://cdn.jsdelivr.net/npm/tinyld@1.1.4/dist/tinyld.light.esm.js

For things related to node, it's ok, node 12 is not that old and even if it's not a LTS anymore, it's still under maintenance until April 2022.
![image](https://user-images.githubusercontent.com/4903529/146311223-8c2f8cdf-326b-40c5-8e58-3e62165f9bd1.png)

But is there any reason why you are stuck and pin on this specific minor version of node `12.18`?
* you should probably be using `12.x` to still get maintenance updates
* it should be quite straightforward to upgrade node from `12.18` to latest node 12 (`12.22.7` at the time)
* the current `12.12.1` was just pick as a requirements because it's the last LTS with important updates

If it's really an issue, I can change this library requirements to a more general `12.x`, but it seems really specific to your case 😄
```json
"node": ">= 12.22.1",
// to
"node": ">= 12.0.0",
```

**Comment by vishnu-shekhawat** [comment]
Hi @kefniark 

thank you for quickly jumping onto this issue.

it would be very helpful, if you can change it to `"node": ">= 12.0.0",` , as we want to provide custom funtionalities by wrapping this library with our custom library, so that it can be used on nodeJS side too

**Comment by kefniark** [comment]
Here you go, I just published a new version on npm `1.1.5` with this modification.
Literally no modification to the code 😺

**Comment by vishnu-shekhawat** [comment]
どうもありがとうございます!!
